INSERT INTO `perfil` (`id`, `nome`) VALUES 
(NULL, 'PADRAO'), 
(NULL, 'GESTOR');

INSERT INTO `usuario` (`id`, `email`, `senha`) VALUES 
(NULL, 'teste@gmail.com', '$2a$10$4gYmDdHsJmrTbBlW8y9.O.EbOUmhtk5QzTwX.ovS//EP64XutdZJm'), 
(NULL, 'challengebackend@alura.com', '$2a$10$4gYmDdHsJmrTbBlW8y9.O.EbOUmhtk5QzTwX.ovS//EP64XutdZJm');

INSERT INTO `perfil_usuarios` (`perfil_id`, `usuarios_id`) VALUES 
('1', '2'), 
('1', '1');

INSERT INTO `categoria` (`id`, `cor`, `titulo`) VALUES
(NULL, '#FFFFFF', 'LIVRE'),
(NULL, '#FFFF00', 'PROGRAMACAO'),
(NULL, '#00BFFF', 'ENTREVISTA');

INSERT INTO `video` (`id`, `descricao`, `titulo`, `url`, `categoria_id`) VALUES 
(NULL, 'O mercado de tecnologia tem crescido bastante, diversas profissões foram surgindo e com elas várias dúvidas. É melhor ser especialista ou generalista? Como se tornar o(a) profissional que as empresas estão procurando? Paulo Silveira responde!', 'Carreiras Hipster em Tecnologia', 'https://www.youtube.com/watch?v=AG8cYHCbGcg&t=34s&ab_channel=AluraCursosOnline', 2), 
(NULL, 'Será que é mesmo tão complicado aprender programação? Preciso de faculdade para estar na área? Neste vídeo, Vanessa Tonini e Gabriel Ferreira falam sobre estas e mais algumas questões relacionadas a programação que não são tão verdades assim (ou nem são)... Confira!', '4 mitos sobre programação', 'https://www.youtube.com/watch?v=yj0FR_gm0sM&t=40s&ab_channel=AluraCursosOnline', 2),
(NULL, 'Você já trabalhou ou trabalha em casa? A Roberta Arcoverde  é uma das pessoas que trabalha neste formato e contou pra gente neste vídeo sobre sua rotina. E você, também trabalha de casa? Conte sobre sua experiência nos comentários! ', 'Como é o trabalho remoto?', 'https://www.youtube.com/watch?v=V0FuAukFSzc&ab_channel=AluraCursosOnline', 2),
(NULL, 'O que é Front-end? Trabalhando na área os termos HTML, CSS e JavaScript fazem parte da rotina das desenvolvedoras e desenvolvedores. Mas o que eles fazem, afinal? Descubra com a Vanessa!', 'O que faz uma desenvolvedora front-end?', 'https://www.youtube.com/watch?v=ZY3-MFxVdEw&ab_channel=AluraCursosOnline', 2),
(NULL, 'Domain Driven Design, o que é? Por que foi criada e qual objetivo dessa linguagem dentro da programação?\r\n\r\nO @Dev Eficiente explicou como funciona o Domain Driven Design e como aplicar essa abordagem de forma estratégica e tática para entregar um software de alta qualidade. Confere aí 😉', 'Domain Driven Design com Alberto Sousa, o Dev Eficiente', 'https://www.youtube.com/watch?v=n40Z1c9Ryog&ab_channel=AluraCursosOnline', 2),
(NULL, 'Neste episódio do Hipsters.tube, Mario Souto e Paulo Silveira conversam sobre o Node .JS, eles explicam o que essa plataforma tão utilizada no universo Front-end faz, como ela surgiu e quais são suas aplicações.', 'O que é Node JS?', 'https://www.youtube.com/watch?v=GKR6uSvEj8w&ab_channel=AluraCursosOnline', 1),
(NULL, 'Por que emuladores e vídeo games antigos são importantes na programação?\r\n\r\nConvidamos o @Fabio Akita  e ele explicou como funcionam os emuladores e a importância de dominar esse software e entender códigos-fontes.', 'Como Funcionam Os Emuladores com Fábio Akita', 'https://www.youtube.com/watch?v=9qx7qjKhJ1Q&t=42s&ab_channel=AluraCursosOnline', 1),
(NULL, 'Daniel Siqueira e David Neves, Instrutores aqui na Alura, ajudam você a entender como este conceito está bastante presente no nosso dia a dia. Vem com a gente, conferir? 😉\r\n\r\n Conheça os cursos de Ciência de Dados da Alura 🔬', 'Crescimento Exponencial', 'https://www.youtube.com/watch?v=tkyDL80-rvU&ab_channel=AluraCursosOnline', '3'), 
(NULL, 'Olá, leitoras e leitores!\r\n\r\nNessa transmissão, vamos falar sobre o livro APIs REST em Kotlin: Seus serviços prontos para o mundo real.\r\n\r\nO Alexandre Saudate, autor do livro, vai comentar sobre o mercado de desenvolvimento Kotlin, diferenças para outras linguagens e influência em futuras versões do Java.', '[Casa do Código] - Lançamento do livro: APIs REST em Kotlin', 'https://www.youtube.com/watch?v=C2sDmYhkgW8&ab_channel=AluraCursosOnline', '2'), 
(NULL, 'Existem vários frameworks para trabalhar na área de Data Science e a Mikaeri Ohana contou pra gente quais são os principais e como eles funcionam.\r\n\r\nConfira o conteúdo e conta pra gente qual framework é essencial na rotina do seu trabalho 🤔', 'Frameworks para Data Science com Mikaeri Ohana', 'https://www.youtube.com/watch?v=I7GtAksNva8&ab_channel=AluraCursosOnline', '2'), 
(NULL, 'Ela sempre gostou muito de estudar e passou de primeira na faculdade de biologia. Se formou, estudou fora, fez mestrado, foi garçonete e hoje trabalha com ciência de dados na Fiocruz.\r\n\r\n▶ Scuba Ponto Dev é um programa que mostra a carreira dos alunos e alunas da Alura. Toda semana!', 'A bióloga cientista de dados: Vanessa Cardoso', 'https://www.youtube.com/watch?v=njCcZNx8Xm0&ab_channel=AluraCursosOnline', '3'), 
(NULL, 'Conteúdo de mobile chegando no Alura+! 🤩\r\n\r\nNeste vídeo, o Luiz Fernando e a Natália Thiel, Instrutor e Instrutora aqui na Alura, falam um pouco mais sobre as diferencias e similaridades do React JS e o React Native e como é usar ambas as ferramentas em seu projeto mobile.', 'Diferenças entre React e React Native', 'https://www.youtube.com/watch?v=2-OAUXA4IcE&ab_channel=AluraCursosOnline', '2'), 
(NULL, 'Ative o sininho para receber um aviso quando a live começar!\r\n\r\nO Bootcamp Front-end vai transformar a sua carreira. Quer saber por quê? Junte-se ao Dev Soutinho, um dos idealizadores do Bootcamp, para tirar todas as suas dúvidas em relação a essa jornada. \r\n\r\nEle vai te apresentar alguns dos principais benefícios do programa e te contar como o Bootcamp pode te ajudar a construir o perfil mais cobiçado do mercado. Tem coisa boa vindo aí!', 'Bootcamp Front End Avançado - Última chance de transformar sua carreira', 'https://www.youtube.com/watch?v=nKj9DsTzFkk&ab_channel=AluraCursosOnline', '1'), 
(NULL, 'Nesse episódio, vamos entender o que é considerado conhecimento básico em front-end e o que é avançado. \r\n\r\nO que alguém que quer trabalhar como front-end junior, pleno e sênior precisa saber? 🤔', 'O que é considerado frontend avançado? | Hipsters.Talks', 'https://www.youtube.com/watch?v=IM5oiFQKNoA&ab_channel=AluraCursosOnline', '2'), (NULL, 'A história de um cara que já formatou muito PC, teve um pet shop, quase foi jogador profissional de League of Legends e se encontoru na tecnologia.', 'O programador que queria ajudar as pessoas: Samuel Pimentel', 'https://www.youtube.com/watch?v=-C5P1Csd5qk&ab_channel=AluraCursosOnline', '3'), 
(NULL, 'A batalha de gigantes começou e no Alura+ desta semana os Instrutores daqui a Alura, Daniel Siqueira e David Neves batem um papo incrível para avaliar prós e contra de cada um dos sistemas. ', 'Google Sheets VS Microsoft Excel', 'https://www.youtube.com/watch?v=08Boqq_NaWc&ab_channel=AluraCursosOnline', '1'), 
(NULL, 'Será que para analisar e trabalhar com dados você precisa, necessariamente, entender muito de Python, R e outras tecnologias de Data Science? \r\n\r\nNesse Hipsters.talks vamos conversar sobre isso e apresentar a nova formação de Data Analysis com Google Sheets da plataforma: um guia para quem quer iniciar na carreira de Análise de dados utilizando o google sheets! ', 'Data Analysis com Google Sheets', 'https://www.youtube.com/watch?v=tt9RrQ3H05o&ab_channel=AluraCursosOnline', '2'), 
(NULL, 'Mais um bate-papo da série em parceria com a Oracle! 🚀\r\n\r\nDessa vez a conversa foi com o Eliel Roger, Associate Tech Consultant na empresa, que contou mais sobre a Oracle Digital Assistant e todas as suas possibilidades pra gente. ', 'O que é a Oracle Digital Assistant?', 'https://www.youtube.com/watch?v=GpVDEjbpFpw&ab_channel=AluraCursosOnline', '3'), 
(NULL, 'Neste Hipsters.talks conversamos com o instrutor Victorino Vila sobre os cursos de Google Data Studio e Big Query da plataforma. \r\n\r\nO papo foi comandado pela Rafa Ballerini e tem muita informação legal! Confere aí 😉', 'Trabalhando com Google Data Studio e Big Query', 'https://www.youtube.com/watch?v=4ik8yUZ2YtY&ab_channel=AluraCursosOnline', '2'), 
(NULL, 'Vamos conversar sobre bancos de dados autônomos? \r\n\r\nEm mais um vídeo da nossa série explicando e explorando as ferramentas da Oracle, recebemos a Jéssica Barbosa, que atua como Cloud Solution Engineer na empresa. ', 'O que é Oracle Autonomous Data Base?', 'https://www.youtube.com/watch?v=H4ImmTlMcEo&ab_channel=AluraCursosOnline', '2'), 
(NULL, 'Em mais um papo do Hipsters.talks, a Rafa Ballerini recebeu o instrutor Guilherme Lima para uma conversa sobre a formação DJango REST que temos na plataforma!', 'Formação Django REST APIs', 'https://www.youtube.com/watch?v=VfxzsJPEGuo&ab_channel=AluraCursosOnline', '3'), 
(NULL, 'Quer aprender a identificar erros com a ferramenta Firebase Crashlytics? Então vem com a gente! 🔥\r\n\r\nNo vídeo de hoje, o Leonardo Marinho, Instrutor aqui na Alura, ensina você a gerar relatórios de erros e exceções utilizando o Crashlytics do Firebase em um aplicativo Flutter. ', 'Registro de exceções no Firebase Crashlytics', 'https://www.youtube.com/watch?v=L0LjsG_eNyY&ab_channel=AluraCursosOnline', '3'), 
(NULL, 'Chegamos ao último vídeo da nossa websérie junto com a Oracle! \r\n\r\nE para finalizar esses conteúdos sobre as ferramentas da empresa, foi a vez de conversarmos com a  Thamires Samira, que é Cloud Solution Engineer, sobre banco de dados como serviço na nuvem.', 'Banco de dados como serviço na nuvem- como funciona?', 'https://www.youtube.com/watch?v=tFEHQLX3wXY&ab_channel=AluraCursosOnline', '3'), 
(NULL, 'Ele tentou por muito tempo ser jogador de futebol, mas se encontrou em tech depois dos 30!', 'O boleiro que mergulhou tecnologia: Thiago Fernandes', 'https://www.youtube.com/watch?v=kGELCpp3E6E&ab_channel=AluraCursosOnline', '1'), 
(NULL, 'Esse é o primeiro vídeo de uma série que fizemos em parceria com a Oracle! 🚀\r\n\r\nNeste primeiro bate-papo, recebemos o Armando Tadeu, que trabalha na empresa como ', 'O que é a Oracle Integration Generation 2?', 'https://www.youtube.com/watch?v=Ut_XoorllmE&ab_channel=AluraCursosOnline', '3'), 
(NULL, 'Recebemos o @Dev Soutinho nesse Hipsters Ponto Tube para falar sobre as melhores práticas com React e como você pode aproveitar melhor as possibilidades dessa tecnologia no cenário atual. ', 'Quais as melhores práticas com React?', 'https://www.youtube.com/watch?v=k77WZrvuDQU&ab_channel=AluraCursosOnline', '3'), 
(NULL, 'O João começou a sua carreira em agronomia e descobriu que o caminho para crescer era mergulhar em tecnologia.', 'O Agrônomo Programador: João Nicoletti', 'https://www.youtube.com/watch?v=nQRZLPvicSU&ab_channel=AluraCursosOnline', '3');



